"""Format-2 project memory: one file per entry, a governed taxonomy and append-only provenance ledgers.

Canonical inputs are `taxonomy.json`, `entries/` and `provenance/`. `INDEX.md` and `catalogs/` are generated
from them and committed so agents can browse within a token budget. The legacy single document is never
stored again; `export()` reproduces it from the store.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

from git_state import ArchiveError, digest
from memory import ID, render as render_legacy

MEMORY_DIR = "specs/memory"
ENTRIES = MEMORY_DIR + "/entries"
CATALOGS = MEMORY_DIR + "/catalogs"
PROVENANCE = MEMORY_DIR + "/provenance"
TAXONOMY = MEMORY_DIR + "/taxonomy.json"
INDEX = MEMORY_DIR + "/INDEX.md"
BASELINE = PROVENANCE + "/0000-baseline.jsonl"
KINDS = ("behavior", "decision", "limit", "follow-up", "dependency", "lesson")
DEFAULT_BUDGETS = {"index": 3000, "catalog_page": 1500, "entry": 1024}
GENERATED = "<!-- Generated by archive.py memory index. Do not edit. -->"
REF = re.compile(r"PM-[a-z][a-z0-9-]*[a-z0-9]")
DOMAIN_ID = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*$")
HEADER_KEYS = ("id", "domain", "kind", "title", "summary", "relations", "selectors")
SELECTOR_KINDS = ("route", "path", "error_code", "config_key")
# Exact names Windows cannot use as a directory (catalogs/<domain id>/).
RESERVED_IDS = {"con", "prn", "aux", "nul", *(f"{p}{n}" for p in ("com", "lpt") for n in range(1, 10))}
# The only file kinds that belong under specs/memory; anything else is a stray.
CATALOG_PAGE = re.compile(r"specs/memory/catalogs/[a-z0-9]+(?:-[a-z0-9]+)*/\d{2,}\.md")
MEMORY_FILE = re.compile(r"specs/memory/(?:entries/[^./][^/]*\.md|catalogs/[a-z0-9]+(?:-[a-z0-9]+)*/\d{2,}\.md"
                         r"|provenance/[^./][^/]*\.jsonl|taxonomy\.json|INDEX\.md)")


def tokens(text: str) -> int:
    # ponytail: chars/4 approximation (owner decision 2026-10-05); swap for a real tokenizer behind this one function.
    return (len(text) + 3) // 4


def domain_id(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")


def _quote(value: str) -> str:
    # JSON string escapes are a subset of TOML basic-string escapes; DEL is the one control TOML also forbids.
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def emit_entry(entry: dict) -> bytes:
    lines = ["+++", f"id = {_quote(entry['id'])}", f"domain = {_quote(entry['domain'])}",
             f"kind = {_quote(entry['kind'])}", f"title = {_quote(entry['title'])}"]
    if entry.get("summary"):
        lines.append(f"summary = {_quote(entry['summary'])}")
    if entry.get("relations"):
        lines.append("relations = [" + ", ".join(_quote(r) for r in entry["relations"]) + "]")
    for selector in entry.get("selectors", []):
        lines += ["", "[[selectors]]", f"kind = {_quote(selector['kind'])}", f"value = {_quote(selector['value'])}"]
    lines += ["+++", entry["text"], ""]
    return "\n".join(lines).encode("utf-8")


def parse_entry(data: bytes, name: str) -> dict:
    text = data.decode("utf-8")
    if not text.startswith("+++\n") or "\n+++\n" not in text:
        raise ArchiveError(f"{name}: entry needs a +++ TOML header.")
    header, body = text[4:].split("\n+++\n", 1)
    try:
        meta = tomllib.loads(header)
    except tomllib.TOMLDecodeError as error:
        raise ArchiveError(f"{name}: invalid TOML header: {error}") from error
    unknown = set(meta) - set(HEADER_KEYS)
    if unknown:
        raise ArchiveError(f"{name}: unknown header keys {sorted(unknown)}.")
    if not body.endswith("\n") or body[:-1] != body[:-1].strip():
        raise ArchiveError(f"{name}: entry text must be trimmed and end with one newline.")
    entry = {key: meta[key] for key in ("id", "domain", "kind", "title") if key in meta}
    entry.update(text=body[:-1], relations=list(meta.get("relations", [])), selectors=list(meta.get("selectors", [])))
    if meta.get("summary"):
        entry["summary"] = meta["summary"]
    if emit_entry(entry) != data:
        raise ArchiveError(f"{name}: entry is not in canonical form; rewrite it with the archive tooling.")
    return entry


def inline_refs(entry: dict) -> list[str]:
    found = REF.findall(entry["title"] + "\n" + entry.get("summary", "") + "\n" + entry["text"])
    return [r for r in dict.fromkeys(found) if r != entry["id"]]


# ---- provenance ledgers -------------------------------------------------

def _line(record: dict) -> bytes:
    return json.dumps(record, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def record_hash(record: dict) -> str:
    return digest(_line(record))


def emit_ledger(header: dict, records: list[dict]) -> bytes:
    return b"".join(_line(r) + b"\n" for r in [header, *records])


def parse_ledger(data: bytes, name: str) -> tuple[dict, list[dict]]:
    lines = data.decode("utf-8").split("\n")
    if lines[-1] != "":
        raise ArchiveError(f"{name}: ledger must end with a newline.")
    try:
        rows = [json.loads(line) for line in lines[:-1]]
    except ValueError as error:
        raise ArchiveError(f"{name}: invalid ledger line: {error}") from error
    if not rows or "ledger" not in rows[0]:
        raise ArchiveError(f"{name}: ledger needs a header line.")
    if emit_ledger(rows[0], rows[1:]) != data:
        raise ArchiveError(f"{name}: ledger is not canonically serialized.")
    return rows[0], rows[1:]


def _expand(header: dict, record: dict) -> tuple[list[dict], list[dict]]:
    if "units" in record:  # compact run form: the commit is the ledger's checkpoint
        commit = header.get("checkpoint")
        if not commit:
            raise ArchiveError(f"{header['ledger']}: compact records need a checkpoint in the header.")
        sources = [{"commit": commit, "path": path, "unit": f"{path}:{line}"}
                   for path, lines in record["units"].items() for line in lines]
        evidence = [{"commit": commit, "path": path} for path in record.get("evidence", [])]
        return sources, evidence
    return list(record.get("sources", [])), list(record.get("evidence", []))


def fold(ledgers: list[tuple[str, dict, list[dict]]]) -> tuple[dict, dict]:
    """Fold ledgers in name order into {entry: {sources, evidence}} and {retired id: replacement}."""
    adds: dict[str, list[tuple[str, list, list]]] = {}
    tombstoned: set[str] = set()
    retired: dict[str, str | None] = {}
    for name, header, records in sorted(ledgers, key=lambda item: item[0]):
        for record in records:
            op = record.get("op")
            if op == "add":
                sources, evidence = _expand(header, record)
                adds.setdefault(record["entry"], []).append((record_hash(record), sources, evidence))
            elif op == "tombstone":
                tombstoned.add(record["record"])
            elif op == "retire":
                retired[record["entry"]] = record.get("replacement")
            else:
                raise ArchiveError(f"{name}: unknown ledger op {op!r}.")
    result = {}
    for entry, items in adds.items():
        sources: list[dict] = []
        evidence: list[dict] = []
        for rid, src, ev in items:
            if rid in tombstoned:
                continue
            sources += [s for s in src if s not in sources]
            evidence += [e for e in ev if e not in evidence]
        result[entry] = {"sources": sources, "evidence": evidence}
    return result, retired


# ---- loading ------------------------------------------------------------

class Store:
    def __init__(self, root: Path):
        self.root = Path(root)
        base = self.root / MEMORY_DIR
        if not (base / "taxonomy.json").is_file():
            raise ArchiveError(f"No format-2 memory at {MEMORY_DIR}.")
        self.taxonomy = json.loads((base / "taxonomy.json").read_text(encoding="utf-8"))
        self.domains = {d["id"]: d for d in self.taxonomy.get("domains", [])}
        self.entries: dict[str, dict] = {}
        for path in sorted((base / "entries").glob("*.md")):
            entry = parse_entry(path.read_bytes(), path.name)
            if path.stem != entry.get("id"):
                raise ArchiveError(f"{path.name}: filename must equal the entry id {entry.get('id')!r}.")
            self.entries[entry["id"]] = entry
        self.ledgers = []
        for path in sorted((base / "provenance").glob("*.jsonl")):
            header, records = parse_ledger(path.read_bytes(), path.name)
            self.ledgers.append((path.name, header, records))
        self.provenance, self.retired = fold(self.ledgers)

    def label(self, domain: str) -> str:
        return self.domains[domain]["label"]


def memory_files(repo_root: Path) -> tuple[list[str], list[str]]:
    """(known memory files, strays) under specs/memory: repo-relative POSIX paths sorted by that string."""
    paths = sorted(p.relative_to(repo_root).as_posix() for p in (Path(repo_root) / MEMORY_DIR).rglob("*") if p.is_file())
    return [p for p in paths if MEMORY_FILE.fullmatch(p)], [p for p in paths if not MEMORY_FILE.fullmatch(p)]


def memory_root(repo_root: Path) -> str:
    # Sorted by POSIX path string (not Path order, which is case-insensitive on Windows); strays are not hashed.
    lines = [f"{p}\0{digest((Path(repo_root) / p).read_bytes())}\n" for p in memory_files(repo_root)[0]]
    return digest("".join(lines).encode("utf-8"))


# ---- generated views ----------------------------------------------------

def _catalog_pages(store: Store, domain: str, budget: int) -> list[str]:
    info = store.domains[domain]
    rows = [f"- [`{e['id']}`](../../entries/{e['id']}.md) · {e['kind']} · {e['title']}"
            for e in sorted((e for e in store.entries.values() if e["domain"] == domain), key=lambda e: e["id"])]
    intro = info.get("definition", "").strip()
    pages: list[list[str]] = [[]]
    for row in rows:
        trial = "\n".join(pages[-1] + [row])
        if pages[-1] and tokens(trial) + 120 > budget:  # 120 ≈ page header and navigation line
            pages.append([])
        pages[-1].append(row)
    rendered = []
    for number, page in enumerate(pages, 1):
        head = [GENERATED, f"# {info['label']}", ""]
        if intro and number == 1:
            head += [intro, ""]
        head += [f"Domain `{domain}` · {len(rows)} entries · page {number} of {len(pages)}", ""]
        rendered.append("\n".join(head + page) + "\n")
    return rendered


def generated(store: Store, budgets: dict | None = None) -> dict[str, bytes]:
    budgets = {**DEFAULT_BUDGETS, **(budgets or {})}
    outputs: dict[str, bytes] = {}
    page_counts = {}
    for domain in sorted(store.domains):
        pages = _catalog_pages(store, domain, budgets["catalog_page"])
        page_counts[domain] = len(pages)
        for number, text in enumerate(pages, 1):
            outputs[f"{CATALOGS}/{domain}/{number:02d}.md"] = text.encode("utf-8")
    counts = {d: sum(1 for e in store.entries.values() if e["domain"] == d) for d in store.domains}
    kinds = {k: sum(1 for e in store.entries.values() if e["kind"] == k) for k in KINDS}
    lines = [GENERATED, "# Project memory", "",
             "Current product behavior, constraints, decisions and open follow-ups, one file per entry. Cite entry ids "
             "such as `PM-admin-error-envelope`.", "",
             "Fastest path: query by what your change touches. The query returns whole, ranked entries within a token "
             "budget, with match reasons and a continuation cursor:", "",
             "`python .specify/extensions/memory/scripts/archive.py memory query --route \"POST /api/v1/...\" "
             "--path src/... --error-code ... --text \"...\" --budget 8000`", "",
             "To browse instead, open the catalog pages below for the domains your change touches, then the "
             "relevant files under `entries/`.", "",
             "Provenance (archived spec sources and code evidence) is kept out of the reading path in "
             "`provenance/*.jsonl`. The full single-document view is `python "
             ".specify/extensions/memory/scripts/archive.py memory export`.", "",
             f"{len(store.entries)} entries: " + ", ".join(f"{n} {k}" for k, n in kinds.items() if n) + ".", "",
             "| Domain | Entries | Catalog |", "|---|---:|---|"]
    for domain in sorted(store.domains, key=lambda d: store.domains[d]["label"].lower()):
        links = " ".join(f"[{n:02d}](catalogs/{domain}/{n:02d}.md)" for n in range(1, page_counts[domain] + 1))
        lines.append(f"| {store.domains[domain]['label']} (`{domain}`) | {counts[domain]} | {links} |")
    outputs[INDEX] = ("\n".join(lines) + "\n").encode("utf-8")
    return outputs


def export(store: Store) -> bytes:
    """Render the legacy single document (memory.render) from the store."""
    legacy = []
    for entry in store.entries.values():
        prov = store.provenance.get(entry["id"], {"sources": [], "evidence": []})
        legacy.append({"id": entry["id"], "domain": store.label(entry["domain"]), "kind": entry["kind"],
                       "title": entry["title"], "text": entry["text"],
                       "sources": prov["sources"], "evidence": prov["evidence"]})
    return render_legacy(legacy)


# ---- validation ---------------------------------------------------------

def check(store: Store, budgets: dict | None = None, retired_ids: set[str] | None = None) -> list[str]:
    budgets = {**DEFAULT_BUDGETS, **(budgets or {})}
    problems: list[str] = []
    retired = set(retired_ids or ()) | set(store.retired)
    ids, labels = [d.get("id", "") for d in store.taxonomy.get("domains", [])], \
        [d.get("label", "") for d in store.taxonomy.get("domains", [])]
    if store.taxonomy.get("schema_version") != 1:
        problems.append("taxonomy.json: schema_version must be 1.")
    if len(set(ids)) != len(ids) or any(not DOMAIN_ID.fullmatch(i) for i in ids):
        problems.append("taxonomy.json: domain ids must be unique kebab-case.")
    problems += [f"taxonomy.json: domain id {i!r} is a reserved Windows name." for i in ids if i in RESERVED_IDS]
    if len(set(labels)) != len(labels) or any(not label.strip() for label in labels):
        problems.append("taxonomy.json: domain labels must be unique and nonempty.")
    for entry in store.entries.values():
        eid = entry["id"]
        if not ID.fullmatch(eid):
            problems.append(f"{eid}: invalid id.")
        if eid in retired:
            problems.append(f"{eid}: id is retired and cannot be live.")
        if entry.get("domain") not in store.domains:
            problems.append(f"{eid}: unknown domain {entry.get('domain')!r}.")
        if entry.get("kind") not in KINDS:
            problems.append(f"{eid}: unknown kind {entry.get('kind')!r}.")
        if not str(entry.get("title", "")).strip() or "\n" in entry.get("title", ""):
            problems.append(f"{eid}: title must be one nonempty line.")
        text = entry["text"]
        if not text.strip():
            problems.append(f"{eid}: empty text.")
        if re.search(r"^#{1,2}\s", text, re.M):
            problems.append(f"{eid}: text cannot contain level-1 or level-2 headings.")
        if re.search(r"\b(?:TODO|TBD|NEEDS CLARIFICATION|UNRESOLVED CONFLICT)\b|^(?:<<<<<<<|=======|>>>>>>>)", text, re.M) \
                or "<!-- archive-entry" in text:
            problems.append(f"{eid}: placeholder, conflict marker or embedded legacy marker in text.")
        if tokens(text) > budgets["entry"]:
            problems.append(f"{eid}: text is {tokens(text)} tokens; the entry budget is {budgets['entry']}.")
        for selector in entry.get("selectors", []):
            if set(selector) != {"kind", "value"} or selector["kind"] not in SELECTOR_KINDS or not selector["value"]:
                problems.append(f"{eid}: invalid selector {selector!r}.")
        for ref in dict.fromkeys(entry.get("relations", []) + inline_refs(entry)):
            if ref not in store.entries and ref not in retired:
                problems.append(f"{eid}: reference {ref} does not resolve to a live or retired entry.")
        prov = store.provenance.get(eid)
        if not prov or not prov["sources"]:
            problems.append(f"{eid}: no provenance sources in any ledger.")
        elif entry.get("kind") == "behavior" and not prov["evidence"]:
            problems.append(f"{eid}: behavior needs implementation evidence.")
    for eid in store.provenance:
        if eid not in store.entries and eid not in retired:
            problems.append(f"provenance: records for unknown entry {eid}.")
    expected = generated(store, budgets)
    known, strays = memory_files(store.root)
    problems += [f"{path}: stray file in {MEMORY_DIR}; remove it." for path in strays]
    actual = {p for p in known if CATALOG_PAGE.fullmatch(p) or p == INDEX}
    for path in sorted(actual - set(expected)):
        problems.append(f"{path}: stray generated file; run `archive.py memory index`.")
    for path, data in expected.items():
        target = store.root / path
        if not target.is_file() or target.read_bytes() != data:
            problems.append(f"{path}: generated view is stale or missing; run `archive.py memory index`.")
        limit = budgets["index"] if path == INDEX else budgets["catalog_page"]
        if tokens(data.decode("utf-8")) > limit:
            problems.append(f"{path}: {tokens(data.decode('utf-8'))} tokens exceeds its budget of {limit}.")
    return problems


# ---- migration ----------------------------------------------------------

def migration_outputs(legacy_entries: list[dict], legacy_sha256: str) -> dict[str, bytes]:
    """Mechanical, lossless conversion of parsed legacy entries; no semantic changes."""
    labels = sorted({e["domain"] for e in legacy_entries}, key=str.lower)
    taxonomy = {"schema_version": 1, "domains": [{"id": domain_id(label), "label": label} for label in labels]}
    if len({d["id"] for d in taxonomy["domains"]}) != len(labels):
        raise ArchiveError("Two domain labels map to the same id; rename one before migrating.")
    outputs = {TAXONOMY: (json.dumps(taxonomy, indent=2, ensure_ascii=False) + "\n").encode("utf-8")}
    records = []
    for legacy in sorted(legacy_entries, key=lambda e: e["id"]):
        entry = {"id": legacy["id"], "domain": domain_id(legacy["domain"]), "kind": legacy["kind"],
                 "title": legacy["title"], "text": legacy["text"], "relations": [], "selectors": []}
        entry["relations"] = inline_refs(entry)
        outputs[f"{ENTRIES}/{entry['id']}.md"] = emit_entry(entry)
        records.append({"op": "add", "entry": legacy["id"], "sources": legacy["sources"], "evidence": legacy["evidence"]})
    header = {"ledger": "0000-baseline", "source": "specs/project-memory.md", "source_sha256": legacy_sha256}
    outputs[BASELINE] = emit_ledger(header, records)
    return outputs
